DNN-10714 - Clear date interval from Datepicker component
dnnsoftware/Dnn.AdminExperience.Extensions pull request #437
Opened 2018-01-22 11:51 UTC by ricardodiasc

2018-01-22 12:07 UTC, tpluscode requested changes

2018-01-22 12:07 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/SearchPage/SearchAdvancedDetails.jsx
> +                                clearChanges={() => {this.toggleDropdownCalendar();this.props.clearAdvancedSearchDateInterval();}}
Please don't do such one-liners. Let's keep each expression in its own line

2018-01-22 12:07 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/DropdownDayPicker/DropdownDayPicker.jsx
> +                                        <Button type="primary" onClick={()=>applyChanges()}>Apply</Button>
Aren't those **Clear**/**Apply** labels coming from a resource file?

2018-01-22 12:07 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/DropdownDayPicker/DropdownDayPicker.jsx
> +                                        <Button type="secondary" style={{"margin-right":"5px"}} onClick={()=>clearChanges()}>Clear</Button>
Would it be possible to move inline styles to the stylesheet?

2018-01-29 20:27 UTC, merged

2018-01-29 20:27 UTC, kanm2015 commented
code review done