DNN-8337
dnnsoftware/Dnn.AdminExperience.Extensions pull request #500
Opened 2018-03-15 20:17 UTC by mean2me

2018-03-15 20:19 UTC, mean2me reviewed
Some files had a mix of LF/CRLF EOL. Set all to LF.

2018-03-16 18:37 UTC, tpluscode requested changes

2018-03-16 18:37 UTC, tpluscode commented on src/Modules/Manage/Dnn.PersonaBar.Roles/Components/IRolesController.cs
> +        List<RoleInfo> GetRolesByNames(PortalSettings portalSettings, int groupId, string commaSeparatedRoles, out List<string> notFound);
About the signature:

1. Passing a comma separated string smells of violated SRP. Please change the parameter to an array/list and move splitting to calling code
1. Please return interfaces instead of concrete implementations. `IList<T>` or `IEnumerable<T>` in this case.
1. `out` parameters are frowned upon outside `TryParse`-like methods. In general were introduced as COM compatibility. Unfortunately C# doesn't (yet) support [anonymous return types][value tuple]. I come up with 4 options:
   1. dedicated class/struct to return, combining both found and not found roles as two fields
   1. strongly typed `Tuple<IList<RoleInfo>, List<string>>` - kind of icky on a public API, because has a weak API
   1. `IDictionary<string, RoleInfo>` - unconventional maybe and also suffers from weak semantics
   1. *my favourite* - just return the found roles and let the caller handle identifying that some/which are missing. this method probably has enough responsibility already

[value tuple]: https://blogs.msdn.microsoft.com/mazhou/2017/05/26/c-7-series-part-1-value-tuples/

2018-03-16 18:37 UTC, tpluscode commented on src/Modules/Manage/Dnn.PersonaBar.Roles/Components/RolesController.cs
> +            return foundRoles;
When `commaSeparatedRoles` is "`NullOrWhiteSpace`" then this method will also return null. When possible please avoid returning null.

2018-03-16 18:37 UTC, tpluscode commented on src/Modules/Manage/Dnn.PersonaBar.Users/Components/Prompt/Commands/AddRoles.cs
> -﻿using System;
I appreciate fixing line endings but it should be done in a separate PR. Now I cannot tell what are the actual code changes 🔍

2018-03-16 18:37 UTC, tpluscode commented on src/Modules/Manage/Dnn.PersonaBar.Roles/Components/RolesController.cs
> +                    bool adminCheck = isAdmin || r.RoleID != portalSettings.AdministratorRoleId;
Mm, I won't question this logic in this particular but I see it occurs in a number of methods in this class. Maybe we could extract it to a shared function?

2018-03-20 14:31 UTC, merged