DNN-19410
dnnsoftware/Dnn.AdminExperience.Extensions pull request #510
Opened 2018-04-16 11:57 UTC by mean2me

2018-04-18 05:19 UTC, tpluscode commented on src/Modules/Settings/Dnn.PersonaBar.SiteSettings/SiteSettings.Web/webpack.config.js
> +                    "NODE_ENV": JSON.stringify("development")
I don't think we really need this constant. It's enough to only ever check for `"production`"

2018-04-18 05:23 UTC, tpluscode requested changes
I did notice this some time ago but I cannot recall why we eventually kept the `reduxImmutableStateInvariant()` 🤔 

Also, I see it appears in pretty much [every single of the projects under this repository](https://github.com/search?q=org%3Adnnsoftware+reduxImmutableStateInvariant&type=Code). Should you change every `configureStore.js`?

2018-04-26 19:53 UTC, mean2me commented
@tpluscode About *reduxImmutableStateInvariant* there many advices on the web about it. Using in a production environment overhead our application.

2018-05-02 09:05 UTC, tpluscode approved these changes

2018-05-02 09:06 UTC, merged

2018-07-25 05:32 UTC, tpluscode commented
fixes #557