Bug/dnn 19500
dnnsoftware/Dnn.AdminExperience.Extensions pull request #514
Opened 2018-04-20 13:28 UTC by Mohtshum

2018-04-25 10:21 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +                if (TabController.IsSpecialTab(tab.TabID, currentPortal.PortalId))
Are you sure this check should be done only for the current portal and not the actual portal coming from the request? Or both?

2018-04-25 10:21 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +            PortalSettings = portalSettings;
Is there no side-effect of setting this property?

2018-04-25 10:21 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +                        TabController.Instance.SoftDeleteTab(tab.TabID, currentPortal);
The if uses `PortalSettings` and the delete uses `currentPortal`. Is that correct?

2018-04-25 10:35 UTC, Mohtshum commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +            PortalSettings = portalSettings;
Nope this is setting for only DeletePage request path

2018-04-25 10:43 UTC, Mohtshum commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +                if (TabController.IsSpecialTab(tab.TabID, currentPortal.PortalId))
Actually currentPortal (more intitutive name) is same as protalSettings but it is rename to it as it is getting initialized against same method i.e. PortalController.Instance.GetCurrentPortalSettings();

2018-04-25 10:46 UTC, Mohtshum commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +                        TabController.Instance.SoftDeleteTab(tab.TabID, currentPortal);
we are only making sure that if portalId is passed as cross-scripting parameter by 

 if (PortalHelper.IsContentExistsForRequestedPortal(tab.PortalID, PortalSettings))

Meanwhile Delete is getting called with same (renamed) parameter.

2018-04-25 13:10 UTC, tpluscode requested changes

2018-04-25 13:10 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +                        TabController.Instance.SoftDeleteTab(tab.TabID, currentPortal);
I see it's the same thing in all those comments. It's too confusing that there is the property, parameter and local variable.

I understand that all of them should be the same? Please use only the method's params and remove usage of the others from this method.

2018-04-27 13:58 UTC, Mohtshum commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +                        TabController.Instance.SoftDeleteTab(tab.TabID, currentPortal);
Now have remove the calls for property PortalSettings object and using the parameter object.

2018-04-27 18:02 UTC, tpluscode approved these changes

2018-04-27 18:02 UTC, merged

2018-07-25 05:23 UTC, tpluscode commented
fixed #574