Bug/dnn 20025
dnnsoftware/Dnn.AdminExperience.Extensions pull request #523
Opened 2018-05-02 11:22 UTC by Mohtshum

2018-05-02 13:20 UTC, tpluscode requested changes

2018-05-02 13:20 UTC, tpluscode commented on src/Dnn.PersonaBar.Extensions.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Dnn.PersonaBar.Common", "Modules\Common\Dnn.PersonaBar.Common\Dnn.PersonaBar.Common.csproj", "{5CFCF09B-8514-448A-AD9D-9173D68F9A1A}"
Actually, please remove the Common project

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Common/Dnn.PersonaBar.Common/ContentVerifier.cs
> +    public class ContentVerifier : ServiceLocator<IContentVerifier, ContentVerifier>, IContentVerifier
Maybe such wrapper is not our best option. `PortalHelper` comes from Admin Experience Library and would be best modified there.

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Common/Dnn.PersonaBar.Common/ContentVerifier.cs
> +        protected override Func<IContentVerifier> GetFactory()
Let's avoid the service locator in new types. This could be just as well instantiated with `new`.

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Common/Dnn.PersonaBar.Common/IContentVerifier.cs
> +    public interface IContentVerifier
Please move this and implementation to AdminExperience.Library.

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PurgePageUnitTests.cs
> +            Assert.IsTrue(!result.IsError);
`Assert.IsFalse` would be cleaner

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PurgePageUnitTests.cs
> +        public void Call_PurgePage_IfPageIdNotExistent_ShouldReturnErrorResponse()
Typo: "Is not existent". Would rename to `PageDoesNotExist` anyway

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PurgePageUnitTests.cs
> +            _tabControllerMock.Setup(t => t.GetTab(It.IsAny<int>(), It.IsAny<int>())).Returns(tab);
Please set up with specific values instead of `It.IsAny`

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PurgePageUnitTests.cs
> +            _contentVerifierMock.VerifyAll();
Please remove the `VerifyAll` calls in these tests

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PurgePageUnitTests.cs
> +            _tabControllerMock.Setup(t => t.GetTab(It.IsAny<int>(), It.IsAny<int>())).Returns(tab);
Ditto

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PurgePageUnitTests.cs
> +            _contentVerifierMock.VerifyAll();
Ditto

2018-05-02 13:20 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PurgePageUnitTests.cs
> +        public void RunAfterEveryTest()
This is not necessary

2018-05-03 10:15 UTC, Mohtshum commented
Please check the changes

2018-05-03 10:24 UTC, tpluscode approved these changes

2018-05-03 10:39 UTC, merged

2018-07-25 05:25 UTC, tpluscode commented
partially fixes #571