Bug/dnn 19865
dnnsoftware/Dnn.AdminExperience.Extensions pull request #528
Opened 2018-05-11 15:15 UTC by Mohtshum

2018-05-14 10:23 UTC, tpluscode requested changes

2018-05-14 10:23 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
>              urlPath = FriendlyUrlController.CleanNameForUrl(urlPath, options, out modified);
What I meant for the tests was to check that this method is called with the local path.

2018-05-14 10:23 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +        public string GetLocalPath(string url)
And this should become private

2018-05-14 10:23 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/IPagesController.cs
> +        string GetLocalPath(string absoluteURL);
This is an implementation detail of the controller. Please remove from interface and verify the call to `FriendlyUrlController.CleanNameForUrl` when calling `ValidatePageUrlSettings`

2018-05-14 11:17 UTC, Mohtshum commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/IPagesController.cs
> +        string GetLocalPath(string absoluteURL);
As FriendlyUrlController.CleanNameForUrl is static method call, then is should be wrapped up in an interface call with same arguments and also need to move the ValidatePageUrlSettings to interface and add all dependencies to injection

2018-05-14 13:24 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/IPagesController.cs
> +        string GetLocalPath(string absoluteURL);
Oh, you are right, `FriendlyUrlController` is not one of it's not one of those singleton service locators. What a pity.

Still, `GetLocalPath` does not belong to the interface. I concur with the idea to wrap `FriendlyUrlController` and mock that. It will be enough to make `ValidatePageUrlSettings` public but without adding it to the interface. Just use a the concrete type in test

2018-05-14 15:28 UTC, Mohtshum commented
Changes pushed for fix in this branch. And the changes for UnitTest would be pushed in [DNN-20362](https://jira.devfactory.com/browse/DNN-20362)

2018-05-14 15:44 UTC, tpluscode approved these changes

2018-05-14 15:44 UTC, merged

2018-07-25 05:24 UTC, tpluscode commented
partially fixes #572