Bug/dnn 20086
dnnsoftware/Dnn.AdminExperience.Extensions pull request #534
Opened 2018-05-21 18:42 UTC by Mohtshum

2018-05-22 12:31 UTC, tpluscode requested changes
Please extract all the `ContentVerifier` to fields and initialise in constructor.

2018-05-23 06:47 UTC, Mohtshum commented
Changes done,  we could go for unit tests for get-page, restore-page

2018-05-23 11:03 UTC, tpluscode approved these changes

2018-05-23 11:12 UTC, tpluscode approved these changes

2018-05-24 08:33 UTC, tpluscode approved these changes

2018-05-24 08:33 UTC, merged