DNN-20086: GetPageDetails getting crashed with null object reference
dnnsoftware/Dnn.AdminExperience.Extensions pull request #538
Opened 2018-05-29 11:51 UTC by Mohtshum

2018-05-29 11:54 UTC, tpluscode requested changes
Also, please add a simple unit test to verify that `PortalController#GetCurrentPortalSettings` is called in case of null parameter

2018-05-29 11:54 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages/Components/PagesControllerImpl.cs
> +            var portalSettings = requestPortalSettings ?? PortalController.Instance.GetCurrentPortalSettings();
I think that with this class we've already moved to constructor-injecting dependencies

2018-05-30 07:23 UTC, Mohtshum commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PagesControllerUnitTests.cs
> +            TestDelegate pageSettingsCall = () =>  _pagesController.GetPageSettings(tabId, null);
GetPageSettings has lots of dependencies, to minimize the change set to validate the null parameter changes are made for exception throwing case.

2018-05-30 07:45 UTC, tpluscode requested changes

2018-05-30 07:45 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PagesControllerUnitTests.cs
> +            TestDelegate pageSettingsCall = () =>  _pagesController.GetPageSettings(tabId, null);
Yeah, I see how this avoids all the setup which would be necessary to test a "happy path". It does verify what we had to verify so that's fine

2018-05-30 07:45 UTC, tpluscode commented on src/Modules/Content/Dnn.PersonaBar.Pages.Tests/PagesControllerUnitTests.cs
> +        PortalSettings _portalSettings = new PortalSettings();
I think I's prefer to keep `TabInfo` and `PortalSettings in individual test methods

2018-05-30 08:01 UTC, tpluscode approved these changes

2018-05-30 08:03 UTC, merged