DNN-20454: Prompt: Cross-portal scripting: "set-user" is not working …
dnnsoftware/Dnn.AdminExperience.Extensions pull request #540
Opened 2018-06-03 11:29 UTC by Mohtshum

…with anything other than the main site (To be general, the site in the URL))

    - Changes made in ValideUser to get the correct or related portalId of the user if accessible
    - Changes made in UnitTest for GetUser for validate user
    - Make Set-User dependencies injectable by constructor 
    - Add unit test for set-user test-cases

2018-06-04 07:29 UTC, tpluscode requested changes
I don't like where `UserValidator` is going. The `ValidateUser` method just keeps getting more responsibilities. It now returns the result model, a user through the `out` parameter and modifies its state.

I think we should take a step back here. Is it really a validator? Looks like this entire function should be split

1. Check if `userId.HasValue` belongs to the command itself. Is there a way to do argument validation?
1. `ConsoleErrorResultModel` also belongs to command code and not users/portals code.
1. The method in general is more of `GetUser` than `ValidateUser`. Maybe it should be moved to `UsersController(Wrapper)` and return a DTO combining the `UserInfo` and `PortalId` instead of using `out` param.

2018-06-04 07:29 UTC, tpluscode commented on src/Modules/Manage/Dnn.PersonaBar.Users.Tests/SetUserUnitTests.cs
> +        }
Small change, but maybe it will be a little bit cleaner to change this to `private SetUser CreateCommand()` and remove the field.

2018-06-04 07:29 UTC, tpluscode commented on src/Modules/Manage/Dnn.PersonaBar.Users.Tests/SetUserUnitTests.cs
> +            SetupCommand(args);
I'd consider simplifying the setup method by putting `"set-user"` inside (it's always the same value anyway) and make the variable portion a `params` argument.

```c#
private void SetupCommand(string userId, params string[] args)
{
}
```

And usage would be more readable

```c#
SetupCommand(
    userId.ToString(),
    "--firstname", "user4", 
    "--lastname", "user4", 
    attributeName, attributeValue)
```

2018-06-04 07:29 UTC, tpluscode commented on src/Modules/Manage/Dnn.PersonaBar.Users/Components/IUserControllerWrapper.cs
> +        UserInfo GetUserById(int portalId, int userId);
:+1:

2018-06-04 14:02 UTC, Mohtshum commented on src/Modules/Manage/Dnn.PersonaBar.Users.Tests/UserValidatorUnitTests.cs
>          }
This file was undone

2018-06-04 15:23 UTC, tpluscode approved these changes

2018-06-04 15:25 UTC, merged

2018-07-25 05:26 UTC, tpluscode commented
fixes #540